apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: java-webapp
  namespace: sample-java-webapp-jenkins-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - image: harbor.example.com/mantislogic/sample-java-webapp-jenkins:{{GIT_COMMIT}}
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /Java_Webapp_Pipeline/rest/hello
              port: 8080
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          name: web
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /Java_Webapp_Pipeline/rest/hello
              port: 8080
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /Java_Webapp_Pipeline/rest/hello
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
