apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: java-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      serviceAccountName: example-sa
      volumes:
        - name: example-pvc
          persistentVolumeClaim:
            claimName: example-pvc
      containers:
        - image: harbor.example.com/mantislogic/sample-java-webapp-jenkins:{{GIT_COMMIT}}
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: KEY1
            - name: KEY2
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: KEY2
            - name: SECRET_ENV
              valueFrom:
                secretKeyRef:
                  name: secret-with-vault
                  key: apikey
          volumeMounts:
          - mountPath: "/tmp"
            name: example-pvc
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /java_webapp_argocd/rest/hello
              port: 8080
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          name: web
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /java_webapp_argocd/rest/hello
              port: 8080
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /java_webapp_argocd/rest/hello
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
